package com.yehorsk.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0042C7)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2B5CE6)
val onPrimaryContainerLight = Color(0xFFE4E7FF)
val secondaryLight = Color(0xFF4C5B95)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFAFBEFF)
val onSecondaryContainerLight = Color(0xFF3C4C84)
val tertiaryLight = Color(0xFF821C9D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9E3BB8)
val onTertiaryContainerLight = Color(0xFFFEDEFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF191B23)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF191B23)
val surfaceVariantLight = Color(0xFFE0E1F4)
val onSurfaceVariantLight = Color(0xFF434655)
val outlineLight = Color(0xFF747686)
val outlineVariantLight = Color(0xFFC3C5D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3039)
val inverseOnSurfaceLight = Color(0xFFF0F0FC)
val inversePrimaryLight = Color(0xFFB6C4FF)
val surfaceDimLight = Color(0xFFD9D9E5)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F2FE)
val surfaceContainerLight = Color(0xFFEDEDF9)
val surfaceContainerHighLight = Color(0xFFE7E7F3)
val surfaceContainerHighestLight = Color(0xFFE2E1ED)

val primaryDark = Color(0xFFB6C4FF)
val onPrimaryDark = Color(0xFF00277F)
val primaryContainerDark = Color(0xFF2B5CE6)
val onPrimaryContainerDark = Color(0xFFE4E7FF)
val secondaryDark = Color(0xFFB6C4FF)
val onSecondaryDark = Color(0xFF1C2D63)
val secondaryContainerDark = Color(0xFF36467E)
val onSecondaryContainerDark = Color(0xFFA6B6F6)
val tertiaryDark = Color(0xFFF3AEFF)
val onTertiaryDark = Color(0xFF55006A)
val tertiaryContainerDark = Color(0xFF9E3BB8)
val onTertiaryContainerDark = Color(0xFFFEDEFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11131B)
val onBackgroundDark = Color(0xFFE2E1ED)
val surfaceDark = Color(0xFF11131B)
val onSurfaceDark = Color(0xFFE2E1ED)
val surfaceVariantDark = Color(0xFF434655)
val onSurfaceVariantDark = Color(0xFFC3C5D7)
val outlineDark = Color(0xFF8D90A0)
val outlineVariantDark = Color(0xFF434655)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E1ED)
val inverseOnSurfaceDark = Color(0xFF2E3039)
val inversePrimaryDark = Color(0xFF1A51DC)
val surfaceDimDark = Color(0xFF11131B)
val surfaceBrightDark = Color(0xFF373942)
val surfaceContainerLowestDark = Color(0xFF0C0E16)
val surfaceContainerLowDark = Color(0xFF191B23)
val surfaceContainerDark = Color(0xFF1D1F28)
val surfaceContainerHighDark = Color(0xFF282A32)
val surfaceContainerHighestDark = Color(0xFF33343D)







